services:
  frontend_v2:
    build:
      context: ./frontend_v2
      dockerfile: Dockerfile
    ports:
      - "20020:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=https://api.kotharicomputers.com

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "20021:3000"
    environment:
      - REACT_APP_API_URL=https://api.kotharicomputers.com
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
      - db-data:/app/db

volumes:
  db-data:
