services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "20020:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=https://api.kotharicomputers.com
      # - REACT_APP_API_BASE_URL_LOCAL=http://localhost:8002
    volumes:
      - ./frontend:/app
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app

