services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "20020:3000"
    environment:
      - REACT_APP_API_URL=http://174.116.118.174:8002
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
      - db-data:/app/db

volumes:
  db-data:
